auth/urls.py
from django.urls import path

from auth.views import login_view, signup_view, logout_view

app_name = 'auth'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
]

dashboard/urls.py
from django.conf.urls import url
from django.urls import path

from dashboard.forms import NewGroupCategoryForm
from dashboard.models import Document, InfoObjectCategory
from dashboard.views import login, qs, DocumentsListView, GroupsListView, CategoriesListView, new_group_view, \
    new_category_form_view

app_name = 'dashboard'
urlpatterns = [
    url(r"^documents/$", DocumentsListView.as_view(model=Document, filterset_fields={'filename': ['icontains'],
                                                                                     'source': ['exact'],
                                                                                     'category': ['exact'],
                                                                                     }), name='documents'),
    url(r"^categories/$", CategoriesListView.as_view(model=InfoObjectCategory,
                                                     filterset_fields={'title': ['icontains'],
                                                                       }), name='categories'),
    path('new-category/', new_category_form_view, name='new_category'),

    path('groups/', GroupsListView.as_view(), name='groups'),

    path('login/', login, name='login'),
    path('quick-start/', qs, name='qs'),
    path('new-group/', new_group_view, name='new_group'),

]

doc_managment/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dashboard.views import index
from doc_managment import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('dashboard/', include('dashboard.urls')),
    path('auth_app/', include('auth_app.urls')),
    path('', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models/category.py
import randomcolor
from django.db import models
from model_utils.managers import InheritanceManager


class InfoObjectCategory(models.Model):
    """ Категория для информационных объектов """
    objects = InheritanceManager()
    title = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.title

    def get_keywords(self, limit=3):
        from dashboard.models import Keyword
        keywords = Keyword.objects.filter(category=self)
        if keywords.__len__() > limit:
            keywords = keywords[:limit]
        rand_color = randomcolor.RandomColor()

        k_dict = {key.word: {"color": rand_color.generate(luminosity='light')[0]} for key in keywords}

        return k_dict


class GroupInfoObjectCategory(InfoObjectCategory):
    group = models.ForeignKey("Group", on_delete=models.CASCADE)

dashboard/models/document.py
from django.db import models

from dashboard.models.information_object import InformationObject


class Document(InformationObject):
    """ Любой файл, который может быть привязан к Информационному объекту """

    filename = models.CharField(max_length=256, null=True, blank=True)
    extension = models.CharField(max_length=10, null=True, blank=True)
    file = models.FileField()
    file_url = models.URLField(null=True, blank=True)  # Ссылка для документов хранящихся вне сервиса.
    size = models.IntegerField(null=True, blank=True)  # В байтах

    def __str__(self):
        return self.filename or self.file.name

    def get_mb_size(self):
        return round((self.size or 0) / 1024 / 1024, 1)

dashboard/models/group.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from doc_managment.settings import INVITE_LINK, INVITE_MESSAGE


class Group(models.Model):
    group_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=128, blank=True)
    administrator = models.ForeignKey(User, on_delete=models.PROTECT)
    chat_id_vk = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return "{name} ({adm})".format(name=self.name, adm=self.administrator.username)

    def get_invite(self):
        return INVITE_LINK.format(uuid=self.group_uuid)

    def get_first_message(self):
        return INVITE_MESSAGE.format(uuid=str(self.group_uuid))

dashboard/models/information_object.py
import randomcolor
from django.db import models
from django.utils.translation import gettext_lazy as _

from dashboard.models.category import InfoObjectCategory
from dashboard.models.group import Group


class InformationObject(models.Model):
    class Source(models.TextChoices):
        MA = 'MA', _("Manually added")
        VK = 'VK', 'Вконтакте'
        TG = 'TG', 'Telegram'
        MAIL = 'EM', _('E-mail')

    source = models.CharField(max_length=2, choices=Source.choices)
    connected_group = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)
    source_id = models.CharField(max_length=256, null=True, blank=True)  # ID в источнике данных
    category = models.ForeignKey(InfoObjectCategory,  # Категории, привязанные к информационному объекту.
                                 null=True, blank=True,
                                 on_delete=models.CASCADE)

    def get_keywords(self, limit=3):
        category = self.category
        k_dict = {}
        if category:
            keywords = list(category.keyword_set.all())
            if keywords.__len__() > limit:
                keywords = keywords[:limit]
            rand_color = randomcolor.RandomColor()
            k_dict = {key.word: {"color": rand_color.generate(luminosity='light')[0]} for key in keywords}
        return k_dict

    def __str__(self):
        return str(self.id)

dashboard/models/keyword.py
from django.db import models


class Keyword(models.Model):
    word = models.CharField(max_length=50, unique=True)
    category = models.ForeignKey("InfoObjectCategory", on_delete=models.CASCADE)

    def __str__(self):
        return self.word

dashboard/models/link.py
from django.db import models

from dashboard.models.information_object import InformationObject


class Link(InformationObject):
    url = models.CharField(max_length=512)
    content = models.TextField(null=True, blank=True)

dashboard/models/profile.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from dashboard.models import Group


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)

    groups = models.ManyToManyField(Group, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

dashboard/forms.py
from django import forms


class NewGroupCategoryForm(forms.Form):
    category_name = forms.CharField(label='Название категории', max_length=100, required=True)
    keyword_1 = forms.CharField(label='Тег 1', max_length=100, required=True)
    keyword_2 = forms.CharField(label='Тег 2', max_length=100, required=False)
    keyword_3 = forms.CharField(label='Тег 3', max_length=100, required=False)

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django_filters.views import FilterView

from dashboard.filter import DocumentFilter, CategoriesFilter
from dashboard.forms import NewGroupCategoryForm
from dashboard.models import Group, InfoObjectCategory, Document, Keyword
from dashboard.models.category import GroupInfoObjectCategory
from doc_managment.settings import MAIN_PAGE


def index(request, *args, **kwargs):
    if request.user.is_authenticated:
        return redirect(MAIN_PAGE)
    else:
        return redirect('auth_app:login')


def login(request, *args, **kwargs):
    return render(request, "auth/login.html")


@login_required
def qs(request, *args, **kwargs):
    return render(request, "dashboard/intro.html")


def new_group_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        new_group = Group.objects.create(administrator=user)
        user.profile.groups.add(new_group)
        user.save()
        new_group.save()
        context = {"group": new_group}
        return render(request, "dashboard/new_group.html", context)
    else:
        return redirect('auth_app:login')


class DocumentsListView(FilterView):
    model = Document
    context_object_name = 'docs'
    filter_class = DocumentFilter
    paginate_by = 100

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(DocumentsListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        new_context = Document.objects.filter(
            connected_group__id__in=[group.id for group in self.request.user.profile.groups.all()]
        )
        return new_context


class GroupsListView(ListView):
    model = Group
    paginate_by = 100

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupsListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        new_context = self.request.user.profile.groups.all()
        return new_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class CategoriesListView(FilterView):
    model = InfoObjectCategory
    context_object_name = 'docs'
    filter_class = CategoriesFilter
    paginate_by = 100

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CategoriesListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            search_str = kwargs['filter'].data['title__icontains']
        except:
            search_str = ""

        obj_list = kwargs.get('object_list')
        if not search_str:
            groups = self.request.user.profile.groups.all()
            global_categories = InfoObjectCategory.objects.all()
            groups_categories = GroupInfoObjectCategory.objects.filter(group__in=groups)
            context['full_categories'] = [
                {"categories": groups_categories,
                 "title": "Персональные категории"},
                {"categories": global_categories,
                 "title": "Глобальные категории"},
            ]
        else:
            context['full_categories'] = [
                {"categories": obj_list,
                 "title": "Найденные категории"},
            ]
        return context

    def get_queryset(self):
        groups = [gr.id for gr in self.request.user.profile.groups.all()]
        excluded_groups = Group.objects.all().exclude(id__in=groups)
        global_categories = InfoObjectCategory.objects.all().select_subclasses().exclude(
            groupinfoobjectcategory__group__in=excluded_groups)
        return global_categories


def new_category_form_view(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NewGroupCategoryForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = form.cleaned_data
            try:
                group = request.user.profile.groups.first()
            except:
                group = None
            cat = GroupInfoObjectCategory(title=data.get("category_name"),
                                          group=group)
            cat.save()
            for kwd in [data.get("keyword_1"), data.get("keyword_2"), data.get("keyword_3")]:
                if kwd:
                    kwd = Keyword(word=kwd, category=cat)
                    kwd.save()

            return redirect("dashboard:categories")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NewGroupCategoryForm()

    return render(request, 'dashboard/new_category.html', {'form': form})

dashboard/templates/dashboard/document_filter.html
{% extends "base.html" %}
{% load static %}
{% load octicons %}



{% block content %}
    <div class="row d-inline-flex justify-content-center">
        <div class="col-md-12" style="min-height: 30rem;">
            <div class="container">

                <div class="row d-flex justify-content-center">
                    <div class="col-md-3">
                        <div class="container">
                            <form class="filter-form new_form" action="" method="get">
                                {{ filter.form.as_p }}
                                <input type="submit" value="Поиск"/>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <h1 class="my-2 light-title">Documents</h1>
                        <div class="table border-dark d-inline-block" style="min-height: 25rem">
                            <table class="w-100">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Имя</th>
                                    <th>Категория</th>
                                    <th>Размер</th>
                                    <th>Загрузка</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for doc in filter.qs %}
                                    <tr>
                                        <td>{{ doc.id }}</td>
                                        <td>{{ doc.document.file.name }}</td>
                                        <td>
                                            <button class="btn btn-no-hover"
                                                    style="background-color: #2aabd2;">
                                                {{ doc.category.title }}
                                            </button>
                                        </td>
                                        <td>{{ doc.get_mb_size }} MB</td>
                                        <td>
                                            <div class="px-2 justify-content-center">
                                                <button class="button btn"><a href="{{ doc.document.file.url }}"
                                                                              target="_blank">
                                                    {% octicon 'desktop-download' width=20 color="#fff" %}
                                                </a></button>
                                            </div>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td>No documents yet</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

dashboard/templates/dashboard/group_list.html
{% extends "base.html" %}
{% load static %}
{% load octicons %}



{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col">
                <h1 class="my-2 light-title">My groups</h1>
                <div class="table border-dark d-inline-block" style="min-height: 25rem">
                    <table class="w-100">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Admin</th>
                            <th>Link</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for group in object_list %}
                            <tr>
                                <td>{{ group.id }}</td>
                                <td>{{ group.name }}</td>
                                <td>{{ group.administrator.username }}</td>
                                <td>
                                    <div class="container px-2 justify-content-center">
                                        <div class="row">
                                            <div class="col-md-10">
                                                <div class="input-group">
                                                    <input type="text" value="{{ group.get_invite }}"
                                                           id="myInput{{ group.id }}">
                                                </div>
                                            </div>
                                            <div class="col-md-2">
                                                <div>
                                                    <button class="button btn" onclick="myFunction({{ group.id }})">
                                                        {% octicon 'clippy' width=20 color="#fff" %}
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td>No groups yet</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

dashboard/templates/dashboard/infoobjectcategory_filter.html
{% extends "dashboard/infoobjectcategory_list.html" %}

dashboard/templates/dashboard/infoobjectcategory_list.html
{% extends "base.html" %}
{% load static %}
{% load octicons %}



{% block content %}
    <div class="container">
        <form action="" method="get">
            <div class="row d-flex justify-content-center filter-form new_form">

                <div class="col-md-8">
                    {{ filter.form.as_p }}
                </div>
                <div class="col-md-2">
                    <p></p>
                    <input type="submit" value="Поиск"/>
                </div>
            </div>
        </form>
        <div class="row d-flex justify-content-center filter-form new_form">
            <div class="col-md-2">
                <p></p>
                <a href="{% url 'dashboard:new_category' %}">
                    <button class="px-2">
                        Создать
                    </button>
                </a>
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <div class="col">
                <h1 class="my-2 light-title">Group Categories</h1>
                <div class="table border-dark d-inline-block" style="min-height: 25rem">
                    <table class="w-100">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Теги</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for local_categories in full_categories %}
                            <tr>
                                <td class="d-inline-flex">
                                    <div class="mx-2">
                                        {% octicon 'git-commit' width=20 color="#fff" %}
                                    </div>
                                    <div class="mx-2 font-weight-bold">
                                        {{ local_categories.title }}
                                    </div>
                                </td>
                                <td></td>
                            </tr>
                            {% for category in local_categories.categories %}
                                <tr>
                                    <td class="table-shift">{{ category.title }}</td>
                                    <td>
                                        {% for word, params in category.get_keywords.items %}
                                            <button class="btn btn-no-hover"
                                                    style="background-color: {{ params.color }};">
                                                {{ word }}
                                            </button>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td class="table-shift font-italic">No categories yet</td>
                                    <td></td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

dashboard/templates/dashboard/informationobject_list.html
{% extends "base.html" %}
{% load static %}
{% load octicons %}



{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col">
                <h1 class="my-2 light-title">Documents</h1>
                <div class="table border-dark d-inline-block" style="min-height: 25rem">
                    <table class="w-100">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Теги</th>
                            <th>Загрузка</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for doc in object_list %}
                            <tr>
                                <td>{{ doc.id }}</td>
                                <td>{{ doc.document.file.name }}</td>
                                <td>

                                    {% for word, params in doc.get_keywords.items %}
                                        <button class="btn btn-no-hover"
                                                style="background-color: {{ params.color }};">
                                            {{ word }}
                                        </button>
                                    {% endfor %}
                                </td>
                                <td>
                                    <div class="px-2 justify-content-center">
                                        <button class="button btn"><a href="{{ doc.document.file.url }}" target="_blank">
                                            {% octicon 'desktop-download' width=20 color="#fff" %}
                                        </a></button>
                                    </div>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td>No documents yet</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.name }} - ${{ obj.price }}<br />
    {% endfor %}



{% endblock content %}

dashboard/templates/dashboard/intro.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="row">
        <div class="container qs-button-block">
            <div class="row d-flex justify-content-center qs-button-block">
                <div class="col-md-3 my-auto">
                    <a href="{% url 'dashboard:new_group' %}">
                        <div class="btn w-100 px-2 qs-button">
                            Создать
                        </div>
                    </a>
                </div>
                <div class="col-md-3 my-auto">
                    <div class="btn w-100 px-2 qs-button" href="{% url 'dashboard:qs' %}">
                        Присоединиться
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock content %}

dashboard/templates/dashboard/new_category.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="row">
        <div class="container qs-button-block filter-form new_form">
            <div class="row d-flex justify-content-center qs-button-block ">
                <div class="col-md-4">
                    <form action="" method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <p></p>
                        <input type="submit" value="Создать"/>
                    </form>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-3">

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

dashboard/templates/dashboard/new_group.html
{% extends "base.html" %}
{% load static %}
{% load octicons %}


{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 align-self-center">
                <p class="font-weight-light">Пригласите бота в групповой чат и отправьте слудующее сообщение.</p>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-3">
                <div class="input-group">
                    <label for="myInput{{ group.id }}">Link</label>
                    <input type="text" value="{{ group.get_first_message }}" id="myInput{{ group.id }}">
                </div>
            </div>
            <div class="col-md-2">
                <div>
                    <button class="button btn" onclick="myFunction({{ group.id }})">
                        {% octicon 'clippy' width=20 color="#fff" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}