auth/urls.py
from django.urls import path

from auth.views import login_view, signup_view, logout_view

app_name = 'auth'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
]

auth_app/urls.py
from django.urls import path

from auth_app.views import login_view, signup_view, logout_view

app_name = 'auth_app'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
]

dashboard/urls.py
from django.conf.urls import url
from django.urls import path

from dashboard.forms import NewGroupCategoryForm
from dashboard.models import Document, InfoObjectCategory
from dashboard.views import login, qs, DocumentsListView, GroupsListView, CategoriesListView, new_group_view, \
    new_category_form_view

app_name = 'dashboard'
urlpatterns = [
    url(r"^documents/$", DocumentsListView.as_view(model=Document, filterset_fields={'filename': ['icontains'],
                                                                                     'source': ['exact'],
                                                                                     'category': ['exact'],
                                                                                     }), name='documents'),
    url(r"^categories/$", CategoriesListView.as_view(model=InfoObjectCategory,
                                                     filterset_fields={'title': ['icontains'],
                                                                       }), name='categories'),
    path('new-category/', new_category_form_view, name='new_category'),

    path('groups/', GroupsListView.as_view(), name='groups'),

    path('login/', login, name='login'),
    path('quick-start/', qs, name='qs'),
    path('new-group/', new_group_view, name='new_group'),

]

doc_managment/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dashboard.views import index
from doc_managment import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('dashboard/', include('dashboard.urls')),
    path('auth_app/', include('auth_app.urls')),
    path('', include('social_django.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
{% load octicons %}
{% load active %}
{% load admin_urls %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'dashboard/images/fav_icon.ico' %}">

    <title>Tuck Dock</title>

    <!-- Bootstrap core CSS -->

    <link href="{% static 'dashboard/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">
    {% block head_tag %} {% endblock %}

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Oswald:300&display=swap" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand navbar-dark bg-top fixed-top">
    <div class="col-md-3 d-flex justify-content-start">
        <div class="d-flex d-lg-block">
            <a class="navbar-brand" href="{% url 'dashboard:documents' %}">Tuck Dock</a>
        </div>
    </div>
    <div class="col-md-6 d-flex justify-content-start">
        {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item {% active '#' %}">
                    <a class="nav-link" href="{% url 'dashboard:qs' %}">Главная</a>
                </li>
                <li class="nav-item {% active '#' %}">
                    <a class="nav-link" href="{% url 'dashboard:documents' %}">Документы</a>
                </li>
                <li class="nav-item {% active '#' %}">
                    <a class="nav-link" href="{% url 'dashboard:groups' %}">Группы</a>
                </li>
                <li class="nav-item {% active '#' %}">
                    <a class="nav-link" href="{% url 'dashboard:categories' %}">Категории</a>
                </li>
            </ul>
        {% endif %}
    </div>
    {% if request.user.is_authenticated %}
        <div class="col-md-3 d-flex justify-content-end">
            <div class="nav-item dropdown d-lg-none">
                <a class="nav-link dropdown-toggle text-light" style="cursor: default"
                   data-toggle="dropdown">
                </a>
                <div class="dropdown-menu dropdown-menu-right" style="left: -6rem">
                    <a class="dropdown-item" href="{% url 'dashboard:documents' %}">Профиль</a>
                    <a class="dropdown-item" href="{% url 'dashboard:documents' %}">Django</a>
                    <a class="dropdown-item" href="{% url 'auth_app:logout' %}">Выход</a>
                </div>
            </div>
            <div class="nav-item dropdown d-none d-lg-block">
                <a class="nav-link dropdown-toggle text-light" style="cursor: default"
                   data-toggle="dropdown">
                    <span class="p-3"> {% octicon 'person' width=15 color='#fff' %} </span>
                    <span>{{ request.user.username }}</span>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'dashboard:documents' %}">Профиль</a>
                    <a class="dropdown-item" href="{% url 'dashboard:documents' %}">Django</a>
                    <a class="dropdown-item" href="{% url 'auth_app:logout' %}">Выход</a>
                </div>
            </div>
        </div>

    {% else %}

        <div class="col-md-3 d-inline-flex justify-content-end">
            <div class="m-1">
                <a class="btn btn-outline-success" href="{% url 'auth_app:login' %}">Вход</a>
            </div>
            <div class="m-1">
                <a class="btn btn-outline-info" href="{% url 'auth_app:signup' %}">Регистрация</a>
            </div>
        </div>

    {% endif %}
</nav>

<main role="main">
    <div class="min-vh-100">
        <div class="container">
            {% block content %} {% endblock %}
        </div>
    </div>
</main><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'dashboard/js/jquery-3.2.1.slim.min.js' %}"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'dashboard/js/jquery-slim.min.js' %}"><\/script>')</script>
<script src="{% static 'dashboard/js/popper.min.js' %}"></script>
<script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dashboard/js/mmodule.js' %}"></script>
</body>
</html>